# Generated by Django 3.2.7 on 2021-12-09 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pha_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=1000)),
                ('manufacture_company_name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=1000)),
                ('dire_for_use', models.TextField(max_length=500)),
                ('storage', models.TextField(max_length=500)),
                ('admin_instruction', models.TextField(max_length=500)),
                ('warning', models.TextField(max_length=500)),
                ('precaution', models.TextField(max_length=500)),
                ('categorie', models.CharField(max_length=100)),
                ('quntity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0)),
                ('genatic_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=1000)),
                ('degree', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
                ('opentime', models.TimeField()),
                ('clostime', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('pharmacy_name', models.CharField(max_length=60)),
                ('Sku_no', models.IntegerField()),
                ('quntity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pha_buss',
            fields=[
                ('doc1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pha_buss', serialize=False, to='pharmacy.pharmacy')),
                ('dates', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pha_Oview',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pha_Oview', serialize=False, to='pharmacy.pharmacy')),
                ('about', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_prod_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('shipping_details', models.TextField(max_length=50)),
                ('card_name', models.CharField(max_length=50)),
                ('card_no', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp_month', models.DateField()),
                ('exp_year', models.DateField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('quntitys', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('payment_status', models.CharField(max_length=30)),
                ('invoice', models.IntegerField()),
                ('pharmacys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pharmacy.pharmacy')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='pharmacy.pha_product')),
            ],
        ),
        migrations.CreateModel(
            name='pha_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('review', models.TextField(max_length=1000)),
                ('YES', models.IntegerField()),
                ('NO', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('dics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_review', to='pharmacy.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pha_product',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_product', to='pharmacy.pharmacy'),
        ),
        migrations.CreateModel(
            name='pha_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_add', models.TextField(max_length=300)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_loc', to='pharmacy.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='pha_highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(max_length=100)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_highlight', to='pharmacy.pha_product')),
            ],
        ),
        migrations.CreateModel(
            name='pha_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_for', models.TextField(max_length=100)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_apply', to='pharmacy.pha_product')),
            ],
        ),
        migrations.CreateModel(
            name='pha_awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_name', models.CharField(max_length=200)),
                ('aw_year', models.DateField()),
                ('aw_desc', models.TextField(max_length=1000)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pha_awards', to='pharmacy.pha_oview')),
            ],
        ),
    ]
