# Generated by Django 3.2.7 on 2021-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacy_prod_order_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='clostime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='opentime',
            field=models.TimeField(null=True),
        ),
    ]
