# Generated by Django 3.2.7 on 2021-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20211225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
