# Generated by Django 3.2.7 on 2021-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_blogs',
            name='ctgry',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dr_blogs',
            name='subctgry',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
