# Generated by Django 3.2.7 on 2021-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_pharmacy', '0002_alter_pharmacy_admin_record_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy_admin_record',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
