# Generated by Django 3.2.7 on 2021-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_pharmacy', '0004_alter_pharmacy_admin_record_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy_admin_record',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
