# Generated by Django 3.2.7 on 2021-12-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('Blood_group', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('prec_name', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctors.dr')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='patient_dashB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('BP_mg', models.IntegerField()),
                ('BP_dl', models.IntegerField()),
                ('body_temp', models.IntegerField()),
                ('Glucose_Level_up', models.IntegerField()),
                ('Glucose_Level_to', models.IntegerField()),
                ('BMI_Status', models.IntegerField()),
                ('Heart_Rate_Status', models.IntegerField()),
                ('FBC_Status', models.IntegerField()),
                ('Weight_Status', models.IntegerField()),
                ('patient_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dashB', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='medical_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('attachment', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='doctors.dr')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='doctors.dr')),
                ('pa_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('card_name', models.CharField(max_length=20)),
                ('card_no', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('exp_month', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='doctors.dr')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='billings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('paid_on_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='doctors.dr')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingss', to='patient.patient_record')),
            ],
        ),
        migrations.CreateModel(
            name='appoinmentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('card_name', models.CharField(max_length=20)),
                ('card_no', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('exp_month', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinmentlist', to='doctors.dr')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinmentlists', to='patient.patient_record')),
            ],
        ),
    ]
