# Generated by Django 3.2.7 on 2021-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20211210_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='prec_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
