# Generated by Django 3.2.7 on 2021-12-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_prescriptions_prec_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinmentlist',
            name='created_date',
        ),
    ]
