# Generated by Django 3.2.7 on 2021-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_appoinmentlist_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmentlist',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
