# Generated by Django 3.2.7 on 2021-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appoinmentlist_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_record',
            name='DOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient_record',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
