# Generated by Django 3.2.7 on 2021-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_record',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
