# Generated by Django 3.2.7 on 2021-12-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_patient_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='appoinment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appoinmentlist'),
        ),
    ]
