# Generated by Django 3.2.7 on 2021-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
