# Generated by Django 3.2.7 on 2021-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0003_hospital_admin_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_categeory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30)),
                ('subcat', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
