# Generated by Django 3.2.7 on 2021-12-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0004_blog_categeory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_categeory',
            name='subcat',
        ),
        migrations.CreateModel(
            name='blog_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_cat', to='Admin_hospital.blog_categeory')),
            ],
        ),
    ]
