# Generated by Django 3.2.7 on 2021-12-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0005_auto_20211213_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_subcategory',
        ),
    ]
