# Generated by Django 3.2.7 on 2021-12-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0006_delete_blog_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
                ('cats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_cat', to='Admin_hospital.blog_categeory')),
            ],
        ),
    ]
