# Generated by Django 3.2.7 on 2021-12-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book_timed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('qulification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('fees_starting', models.IntegerField(max_length=5)),
                ('fees_end', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Dr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='servies_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='specifications_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Buss_Ho',
            fields=[
                ('doc1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Buss_Ho', serialize=False, to='doctors.dr')),
                ('dates', models.DateField(auto_now_add=True)),
                ('T1', models.TimeField()),
                ('T2', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ov_view',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Ov_view', serialize=False, to='doctors.dr')),
                ('about', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'patient'), ('2', 'doctor'), ('3', 'pharmacy'), ('4', 'admin'), ('5', 'Pharmacy_admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userType', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('review', models.TextField(max_length=1000)),
                ('YES', models.IntegerField()),
                ('NO', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('dics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reView', to='doctors.dr')),
            ],
        ),
        migrations.CreateModel(
            name='mypatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dr_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypatients', to='doctors.dr')),
            ],
        ),
        migrations.CreateModel(
            name='Loca_tions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinics_name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('clinic_add', models.TextField(max_length=300)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loca_tions', to='doctors.dr')),
            ],
        ),
        migrations.CreateModel(
            name='for_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('day', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_booking', to='doctors.dr')),
            ],
        ),
        migrations.CreateModel(
            name='book_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_times', to='doctors.for_bookings')),
                ('times', models.ManyToManyField(related_name='book_timed', to='doctors.book_timed')),
            ],
        ),
        migrations.CreateModel(
            name='Specific_ation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.ManyToManyField(related_name='Specific_ationss', to='doctors.specifications_add')),
                ('dr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Specification', to='doctors.ov_view')),
            ],
        ),
        migrations.CreateModel(
            name='servi_ses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servics', models.ManyToManyField(related_name='servies_add', to='doctors.servies_add')),
                ('dr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servi_ses', to='doctors.ov_view')),
            ],
        ),
        migrations.CreateModel(
            name='Hour_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time1', models.TimeField()),
                ('Time2', models.TimeField()),
                ('Day', models.CharField(max_length=20)),
                ('dic2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hour_S', to='doctors.buss_ho')),
            ],
        ),
        migrations.CreateModel(
            name='Exp_erince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_filled', models.CharField(max_length=200)),
                ('YO_exp_start', models.DateField()),
                ('YO_exp_till', models.DateField()),
                ('experince', models.CharField(max_length=100)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exp_erince', to='doctors.ov_view')),
            ],
        ),
        migrations.CreateModel(
            name='Educat_ion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univercity', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('YOA', models.DateField()),
                ('YOP', models.DateField()),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Educat_ion', to='doctors.ov_view')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_name', models.CharField(max_length=200)),
                ('aw_year', models.DateField()),
                ('aw_desc', models.TextField(max_length=1000)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Awards', to='doctors.ov_view')),
            ],
        ),
    ]
