# Generated by Django 3.2.7 on 2021-12-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypatient',
            name='pa_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypatient', to='patient.patient_record'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reViewS', to='patient.patient_record'),
        ),
    ]
