# Generated by Django 3.2.7 on 2021-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20211209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='loca_tions',
            name='closetime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='loca_tions',
            name='opentime',
            field=models.TimeField(null=True),
        ),
    ]
