# Generated by Django 3.2.7 on 2021-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20211210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='fees_starting',
            field=models.IntegerField(),
        ),
    ]
