# Generated by Django 3.2.7 on 2021-12-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_record_mobile'),
        ('doctors', '0005_alter_review_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='rvw_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('review', models.TextField(max_length=1000)),
                ('YES', models.IntegerField()),
                ('NO', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reView_rply', to='doctors.dr')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reViewS_rply', to='patient.patient_record')),
                ('rvw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reView_rplyss', to='doctors.review')),
            ],
        ),
    ]
