# Generated by Django 3.2.7 on 2021-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20211212_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
