# Generated by Django 4.0 on 2022-01-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_hospital', '0007_blog_subcategory'),
        ('doctors', '0011_dr_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Drs', to='Admin_hospital.speciality'),
        ),
    ]
